### ISSUE TITLE
Card not displaying Wh > kWh correctly

### ISSUE THREAD

**Issue by nathan-curtis** [Neuvidor/system-energy-flow-card#1]
Card not displaying Wh > kWh correctly

Card set to display one grid entity using this configuration:
type: custom:system-energy-flow-card
watt_threshold: 0
kwh_decimals: 1
wh_decimals: 0
entities:
  grid:
    consumption: sensor.cps_energy_monthly_total
    
Consumption sensor is an enetgy meter entity as follows:

unit_of_measurement: Wh
icon: mdi:meter-electric
friendly_name: CPS Energy Monthly total

But when the card displays kWh, it is not doing the math to convert from Wh > kWh and just appends KWh without recaluulating hte numeric displat - therefore it's 3 orders of magnitude off.

Entity in Dev tools:
![image](https://user-images.githubusercontent.com/24819138/222549534-2b9c1732-f20f-44f7-a5d6-e69c13e8c958.png)

Card:
![image](https://user-images.githubusercontent.com/24819138/222549675-6f1c09ad-2879-4db1-8c3c-aa5832c583c1.png)

**Comment by Neuvidor** [comment]
Dear,

Could you try the v2023.03.02 beta version and keep me informed ?

**Comment by michas79de** [comment]
Same issue for me.

I've downloaded it again and in HACS I'm seeing now:
![grafik](https://user-images.githubusercontent.com/49291708/223571355-da87ca7e-2e9e-4331-9d26-59578871bc65.png)
browser cache cleaned, HA restarted, browser tab reloaded, but:
![grafik](https://user-images.githubusercontent.com/49291708/223571634-8f73cf2f-8473-4ae5-903f-5b7f12750efe.png)
(treshold: 1000)

**Comment by michas79de** [comment]
Sorry for writing "Same issue for me." three weeks ago. I didn't read the op correctly.

My issue is that values below the threshold aren't "Wh" but "W".
So the numbers were correct calculated but the unit is wrong!

If I click in HA | HACS | Frontend | System Energy Flow Card | Three Dots Menu | Quelldateien öffnen (open source files) I can find exactly one "kWh" and close to it a "W" in the same line of code:

`return"W"===e.attributes.unit_of_measurement?i:1e3*i},this.displayValue=t=>null===t?0:t>=this._config.watt_threshold?`${ut(t/1e3,this._config.kwh_decimals)} **kWh**`:`${ut(t,this._config.wh_decimals)} **W**`}setConfig(t){if(!t.entities||!t.entities.battery&&!t.entities.grid&&!t.entities.solar)throw new Error("At least one entity for battery, grid or solar must be defined");`

@Neuvidor Maybe there has to be a "Wh", or?

**Comment by Neuvidor** [comment]
Thanks [michas79de](https://github.com/michas79de) for your last message.
I forgot to do all changes regarding decimals and unit into the "system-energy-flow-card.js" file.

This is now done, I have publish a new Beta version.
Could you please tell me if it's OK for you ?

Sorry for this mistake, this is my first repository so I'm not very confortable regarding coding.
Many thanks to all for helping me through issue reporting.

**Comment by michas79de** [comment]
> I have publish a new Beta version. Could you please tell me if it's OK for you ?

I have now installed v2023.3.25v1 (even uninstalled and installed instead of just updating), cleaned the cache and restarted HA, but I can't see any change.
There is still W instead of Wh:
![grafik](https://user-images.githubusercontent.com/49291708/227743105-1420d893-80af-485b-bc03-d41fc0614ddb.png)
my setting:

> type: custom:system-energy-flow-card
entities:
  grid:
    consumption: sensor.strom_tagesverbrauch
    production: sensor.strom_tageseinspeisung
  solar: sensor.strom_tageserzeugung
watt_threshold: 1000
wh_decimals: 0
kwh_decimals: 2

**Comment by Neuvidor** [comment]
@michas79de, could you please open a new issue LinkedIn to your issue with the description because this original issue is now solved. 

@nathan-curtis, can you confirm ?

**Comment by Neuvidor** [comment]
Hello @nathan-curtis,

Could you confirm that Wh to kWh is now working for you with the last Beta version ?
It works on my side.

## Result :
* ![image](https://user-images.githubusercontent.com/64861851/227761092-929276ae-c82b-4669-a40c-f7b6ce877407.png)

## Entity description :
* ![image](https://user-images.githubusercontent.com/64861851/227761188-91dc63e3-b73d-4ffd-a9f7-dba88db8c57e.png)

**Comment by nathan-curtis** [comment]
> Hello @nathan-curtis,
> 
> Could you confirm that Wh to kWh is now working for you with the last Beta version ? It works on my side.

Confirmed Its working with the latest beta.
![image](https://user-images.githubusercontent.com/24819138/227798496-d9b4e916-3e6d-4a34-a2db-45608cc17a6b.png)
