### ISSUE TITLE
card shows "W" instead of "Wh" (kWh is correct)

### ISSUE THREAD

**Issue by michas79de** [Neuvidor/system-energy-flow-card#3]
I have correct values but wrong unit (W instead of Wh for small values below the threshold).

I've downloaded it again and in HACS I'm seeing now:
![grafik](https://user-images.githubusercontent.com/49291708/223571355-da87ca7e-2e9e-4331-9d26-59578871bc65.png)
browser cache cleaned, HA restarted, browser tab reloaded, but:
![grafik](https://user-images.githubusercontent.com/49291708/223571968-e4c24f41-1823-4f12-8be0-2f5c56abe6ef.png)

If I go to HA | HACS | Frontend | System Energy Flow Card | Three Dots Menu | Open Source Files I can find exactly one "kWh" and next to it a "W" in the same line of code:

`return"W"===e.attributes.unit_of_measurement?i:1e3*i},this.displayValue=t=>null===t?0:t>=this._config.watt_threshold?`${ut(t/1e3,this._config.kwh_decimals)} **kWh**`:`${ut(t,this._config.wh_decimals)} **W**`}setConfig(t){if(!t.entities||!t.entities.battery&&!t.entities.grid&&!t.entities.solar)throw new Error("At least one entity for battery, grid or solar must be defined");`

@Neuvidor Maybe there has to be a "Wh", or?

**Comment by michas79de** [comment]
https://github.com/Neuvidor/system-energy-flow-card/issues/1#issuecomment-1483917722

> I have publish a new Beta version. Could you please tell me if it's OK for you ?

I have now installed v2023.3.25v1 (even uninstalled and installed instead of just updating), cleaned the cache and restarted HA, but I can't see any change.
There is still W instead of Wh:
![grafik](https://user-images.githubusercontent.com/49291708/227743105-1420d893-80af-485b-bc03-d41fc0614ddb.png)
my setting:

> type: custom:system-energy-flow-card
entities:
  grid:
    consumption: sensor.strom_tagesverbrauch
    production: sensor.strom_tageseinspeisung
  solar: sensor.strom_tageserzeugung
watt_threshold: 1000
wh_decimals: 0
kwh_decimals: 2

**Comment by Neuvidor** [comment]
Thanks for opening this new issue.
I have publish now a ne beta version v2023.3.26v1, could you try ?

**Comment by michas79de** [comment]
Now it's fine with v2023.3.26v1.
Thank you very much!
